### ISSUE TITLE
Only administrators Are Able to View All Batch Jobs

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#27]
### Description
As a batch administrator, I want to view every batch system-wide from my batch job dashboard.

### Done Looks Like
- When an admin-level user navigates to the batch dashboard, they see every job created in the system
- Other than viewing all batch jobs, the interface is the same as for non-admin users (i.e. different views for batch job list, batch job detail, and batch item detail)

**Comment by yingfeng-iu** [comment]
From what I understand (in abiliity.rb), the current permission checking logic allows admin user to do everything with batch (upload, list, show, edit, delete); but any other user will not be able to do anything above. Thus, the remaining task of this story is to add logic for non-admin users, to allow them to create (upload) new batch, list/show/edit/delete all batches they created, is that correct?

**Comment by yingfeng-iu** [comment]
This seems to be closely related to https://github.com/samvera-labs/hyrax-batch_ingest/issues/51

**Comment by cjcolvar** [comment]
@yingfeng-iu While it isn't clear from the done looks like, I believe this ticket is meant to cover only the administrator case.  So I think this is done when:
- [ ] administrators can do anything with batches
- [ ] non-administrators can do nothing (including even getting to the batches list, view, and upload pages)
So I think the remainder of this work is ensuring that the access controls are applying to all users which should block non-admin users given what is currently in the ability.

**Comment by yingfeng-iu** [comment]
https://github.com/CanCanCommunity/cancancan/wiki/authorizing-controller-actions

**Comment by yingfeng-iu** [comment]
1) I did find load_and_authorize_resource in MyController, but it's only for show. 
2) this turns out to be hyrax bug, see https://github.com/samvera/hyrax/issues/3444. I created a new local branch to fix this, but couldn't push the branch (permission denied) to hyrax. 
3) from Chirs: Chris Colvard [8:53 AM]
@Ying I’m looking at your questions and now wondering if it is cleaner and clearer to make the `ApplicationController` not subclass `Hyrax::MyController` and instead just include the things we really care about:
```include Hydra::Controller::ControllerBehavior
include Hyrax::Controller
with_themed_layout 'dashboard'```
The code that handles the access control denied cases is spread across those two mixins:
https://github.com/samvera/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb#L13
https://github.com/samvera/hyrax/blob/4d7974614584a5ea73761da1c29be1759df88c39/app/controllers/concerns/hyrax/controller.rb#L35-L67
That last one explains the 401 vs 403…it looks like Hyrax’s preference is for 401 when returning html but 403 when returning json.
As for the 301 redirect I’m not sure without knowing what it is being redirected to…it could be a test setup issue
4) we decided to keep inheriting MyController for now, in case we need solr/blacklight customization.
