### ISSUE TITLE
Batch dashboard navigation from Hyrax Dashboard

### ISSUE THREAD

**Issue by sroosa** [samvera-labs/hyrax-batch_ingest#74]
### Descriptive
You can get to the batch dashboard from the main Hyrax dashboard

### Done Looks Like
- Users can click a link in the Hyrax administrative dashboard to get to the batch object detail page
- Only users who have rights to view a batch should see this link
- Installing the gem will add this link to the dashboard (if practical)

**Comment by cjcolvar** [comment]
I'm thinking that we'll want to add it here but there isn't an way to do this without overridding hyrax views right now.
https://github.com/samvera/hyrax/blob/master/app/views/hyrax/dashboard/sidebar/_activity.html.erb#L29-L33

**Comment by cjcolvar** [comment]
@joncameron votes for the link to be between "Your Activity" and "Reports".

**Comment by sroosa** [comment]
@cjcolvar I agree with @joncameron. Let's do it that way.

**Comment by davidschober** [comment]
I'm thinking it should be under repository contents. Everything under "tasks" is about taking actions on existing repository content, where "repository content" is about creating items within the repository.

**Comment by sroosa** [comment]
+1

**Comment by yingfeng-iu** [comment]
view path: https://stackoverflow.com/questions/9769337/rails-prepend-view-path-of-mountable-engine/26606926#26606926

**Comment by yingfeng-iu** [comment]
I've moved the batch link to the Repository Content sidebar. I've tried different ways to make the overwriten sidebar partial working, but so far each way got stuck with some issues:

1. using prepend_view_path: I tried calling this to add the BatchIngest Engine view path to the front of the view path stack, 
1a) from inside ApplicationController using before_filter
1b) from a new DashboardController class which extends the Hyrax DashboardController, using either before_filter or 
1c) included_do (as shown in https://github.com/samvera-labs/hyrax-iiif_av/blob/master/app/controllers/concerns/hyrax/iiif_av/controller_behavior.rb)
Neither of the above approach takes effect. I set breakpoint and none of them got execeuted. Perhaps I'm not adding to the right controller. 

2. Even if #1 worked, it still has the drawback of disallowing the Avalon app to overwrite the BatchIngest Engine's view, because the latter is at the front of the view stack. So followed Answer#2 at https://stackoverflow.com/questions/9769337/rails-prepend-view-path-of-mountable-engine/26606926#26606926, inserting the BatchIngest view path in before Hyrax Engine view path, but after the internal app view path. This does take effect. The breakpoint does stop here, and I can see that even before I insert the BatchIngest view path, it already exists but at the bottom (end) of the stack; after insert, it does appear at the spot as expected. However, when I run my tests, I got error that hyrax.batches_path is not defined. This definitely is caused by the order change of the view paths. Interestingly, the other paths such as hyrax.my_collections_path and hyrax.my_works_path still work. I'm not sure how to fix it though. The error msg is as follows:

ActionView::Template::Error: undefined method `batches_path' for #<ActionDispatch::Routing::RoutesProxy:0x0000561b3f70ff98>

  0) hyrax/dashboard/sidebar/_repository_content.html.erb as any logged in user has the Collection link
     Failure/Error: <%= menu.nav_link(hyrax.batches_path) do %>
     
     ActionView::Template::Error:
       undefined method `batches_path' for #<ActionDispatch::Routing::RoutesProxy:0x0000561b3f70ff98>
     # ./app/views/hyrax/dashboard/sidebar/_repository_content.html.erb:14:in `__home_yingfeng__rojects_hyrax_batch_ingest_app_views_hyrax_dashboard_sidebar__repository_content_html_erb___1111971213179692907_47337514559180'
     # ./spec/views/hyrax/dashboard/batch_sidebar_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `batches_path' for #<ActionDispatch::Routing::RoutesProxy:0x0000561b3f70ff98>
     #   ./app/views/hyrax/dashboard/sidebar/_repository_content.html.erb:14:in `__home_yingfeng__rojects_hyrax_batch_ingest_app_views_hyrax_dashboard_sidebar__repository_content_html_erb___1111971213179692907_47337514559180'

**Comment by cjcolvar** [comment]
@yingfeng-iu Instead of `hyrax.batches_path` try `hyrax_batch_ingest.batches_path`.

**Comment by yingfeng-iu** [comment]
thanks Chris, that worked. so where is hyrax or hyrax_batch_ingest defined? I thought it was some naming convention corresponding to the view path, but after I added the config to change view path, the route list didn't show any difference. So I wonder how the config change made the difference between hyrax vs hyrax_batch_ingest.
