### ISSUE TITLE
Selecting Error on a Batch Item Returns Error Details

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#79]
### Description
As a user, I want to optionally view a detailed error message on what went wrong with one of my submitted batch items.

### Done Looks Like
- When a user clicks an Error value in the Status column, it displays the error returned by the application on why that item didn't complete.

### Note
This is for the batch detail view only. Users are expected, if they find that a batch object that contains an error, to go into the detail view to find more detailed information on the batch items themselves.

**Comment by cjcolvar** [comment]
This would be implemented by the failed row items accordion expanding to reveal the error message.  All other rows would do nothing when clicked.  This leaves a row with 3 columns (status, id within batch, repository id).  The accordion expansion would be advertised to the user via color change highlighting.

Source location seems like it could be dropped entirely since id within batch should contain similar data for AMS and will never contain anything for Avalon.  FWIW the analogous  field source_data isn't displayed.

@sroosa @joncameron @davidschober Thoughts?

**Comment by sroosa** [comment]
@cjcolvar that makes sense to me. Getting the filename from the id within batch column should be plenty to direct them back to the errored file.

**Comment by joncameron** [comment]
👍

**Comment by yingfeng-iu** [comment]
https://github.com/nulib/donut/blob/master/app/views/batches/show.html.erb

**Comment by yingfeng-iu** [comment]
![image](https://user-images.githubusercontent.com/21180528/50790154-26f7b480-128c-11e9-8121-27ea1c8bb260.png)
