### ISSUE TITLE
Determine Batch Format

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/hyrax-batch_ingest#8]
## Description

Fields in CSV format will correspond to values in a work type, allowing for dynamic adding of new fields as work type changes or other changes occur in the application. Note currently in NU batch, if a field exists in the model it should be accessible via batch.

### Requirements
- Fields are available for an existing item ID which would add the contents of a row to a pre-existing item in the system
- Metadata fields are available for any work type

## Done looks like
- rules set up for how batch columns work and are named
- repeatable field rules are documented. 

## Notes

Below are NU's current batch ingest instructions.

**Comment by davidschober** [comment]
## Redacted how to from NU's docs

## Connecting to the dropbox with Cyberduck

Batch ingestion via spreadsheet is done through the AWS dropbox, which can be accessed with Cyberduck. Go to the [Connecting to the dropbox page](redacted) to learn how to set up the dropbox.

## Uploading to the dropbox

First, create a folder in the dropbox for the files you want to ingest into DONUT (this step isn't mandatory, but it helps keep the dropbox organized). In Cyberduck, click the "Action" button and choose "New Folder." Then enter the folder name - use something descriptive, like the collection name ("Berkeley Folk Music Festival Collection") - and press "Create."
![cyberduck actions-upload image](images/CYBERDUCK_newfolder.jpg)

<br/>

Next, add the files you want to ingest into DONUT to the folder you created in the dropbox. There are two ways of starting an upload into the dropbox with Cyberduck. You can either drag the files you want to ingest onto the Cyberduck window, which will start an upload into the dropbox, or you can click the "Action" button on Cyberduck and choose "Upload" to select the files you want to ingest.
![cyberduck actions-upload image](images/CYBERDUCK_upload.jpg)

## Initiating the batch ingest

The batch ingest will begin when you upload a spreadsheet (in .csv format) to the dropbox. This spreadsheet should contain metadata that corresponds to the files you want to ingest into DONUT.
Note: the batch ingest will begin **as soon as** you upload the spreadsheet, so do not upload it until all of the files you want to ingest are finished uploading into the dropbox. If you add the spreadsheet before the files are finished uploading, you will get "file not found" errors in DONUT.

### Formatting the spreadsheet

Start with this [spreadsheet template](files/batch_ingest_template.xlsx). Each column contains a different metadata field; each row will create a different work in DONUT.

* The metadata columns are organized left to right with: required metadata fields (green), administrative metadata fields (blue), descriptive metadata fields (yellow), and extended descriptive metadata / relators (peach)
* The columns are color-coded by the different metadata types for ease of use
* The template contains every metadata field possible in DONUT. Note that you can delete any column except for the required metadata fields (admin set id, accession number, type, title, date created, preservation level, rights_statement, status, and file name) and the batch ingest will still work.
* Don't worry about colors, fonts, etc. At the end you'll save the spreadsheet as a .csv file, which will strip out any formatting.  

* The columns in the template spreadsheet contain notes on the metadata that should be added to each. For additional guidance, see the the guides to metadata: [Administrative metadata in DONUT](https://github.com/nulib/next-generation-repository/wiki/Administrative-Metadata-in-DONUT) and [Descriptive Metadata in DONUT](https://github.com/nulib/next-generation-repository/wiki/Descriptive-Metadata-in-DONUT). There is also an example spreadsheet with corresponding files left in the dropbox: [sample spreadhseet with data](files/batch_test_with_email_recto_verso_clean.csv).

* The **file** column is not a metadata field. It should contain the filename of the file to be ingested, with the file extension (i.e. postcard1.tif).  

* The **type** column is not a metadata field either; this field tells DONUT what metadata model it should be using. For ingesting images, the type column should contain ` Image`. Note that it must be capitalized, or DONUT will not successfully perform the ingest.

* **To create a work with multiple files associated with it,** as many additional "file" columns to the spreadsheet as are necessary. For example, if the batch you're ingesting contains postcards that consist of two images each, recto and verso, the spreadsheet should be modified like this:
![batch spreadsheet multipage example image](images/BATCH_multipage.png)

* When you are finished adding metadata to the spreadsheet, save it as a .csv file (the name of the spreadsheet doesn't matter, though it helps to keep it descriptive for later reference, i.e. "BFMFbatch1_20180601.csv"). Then upload your .csv to the DONUT dropbox, adding it to the main dropbox, not to any folders you have created (see note below about file paths). Your batch ingest should begin immediately.

### Important notes
* Filenames must be entered with their path relative to the spreadsheet. This means that if you organized the files you want to ingest in a folder within the dropbox, but the spreadsheet will be be in the top level of the dropbox (i.e. not in the folder), the folder name has to be in the spreadsheet. For example, if the folder is called "PostcardCollection," the file column would contain ` PostcardCollection/postcard1.tif` However, if your files and your spreadsheet are in the same folder (top level or a subfolder that you have created) no path is necessary, just enter the filename with the extension.
![batch relative paths image](images/BATCH_relativepaths.jpg)

* The spreadsheet **must** be uploaded to the dropbox as a .csv file for the batch ingest to begin. If your batch hasn't started after a few minutes, check to see if you accidentally used an .xls or .xlsx. DONUT doesn't recognize these spreadsheet formats.
* DONUT displays the [progress of batch ingests](http://donut.repo.rdc-staging.library.northwestern.edu/batches?locale=en), but this feature is only available to logged in repository administrators.

## Common errors in batch ingest
If you are a repository administrator, you can see if your batch ingest threw any errors. Go to the [batch progress page](http://donut.repo.rdc-staging.library.northwestern.edu/batches?locale=en) and click on your batch. DONUT lists each row of your spreadsheet and the status - "in progress" means that the batch ingest is still working. "Success" means that the work was successfully created in DONUT. Any errors are listed with an error message and the row number in which the error was found (note that DONUT ignores the first two rows of the spreadsheet that contain your email and the metadata headings, so the row number for errors corresponds to n+2 in your spreadsheet).
Some common errors are explained below:

* If any required metadata fields are missing, DONUT will display an error like "No accession number: batch entry must have an accession number." Make sure all required metadata is in the spreadsheet
* **Invalid format (URI expected):** this error occurs when DONUT expects a URI and encounters something else. For more about URIs, see the METADATA INFO WIKI
* **date created: Invalid EDTF date:** dates must conform to EDTF format. Change the date formats in the spreadsheet where necessary.
* **Invalid headers:** this error means that one of the column headers is wrong. Check the column headers for typos, or re-download the [batch ingest template](files/batch_ingest_template.xlsx) to make sure you have the correct headers.
* **Aws::S3::Errors::NotFound:** this error means that DONUT couldn't find the file referenced in this row. This could be because the file is not in the dropbox, the filename on the spreadsheet is incorrect, or the relative path is wrong (see note above on relative paths).
* **ActiveRecord::RecordNotFound: Couldn’t find Hyrax::PermissionTemplate** This occurs if you've used an invalid 'Admin Set' ID.
* **Skipped**: DONUT checks all accession numbers to make sure that they are unique, and will not create a new work if it finds a work already existing with that accession number. If you encounter this error unexpectedly, search in DONUT for the accession number you are trying to ingest. Edit or delete that work if necessary, then re-ingest. Generally, you can ignore "skipped" in a DONUT batch ingest.
* **batch: invalid byte sequence in UTF-8** Encoding of the .csv file is not in UTF-8. Quickfix: import original .xlsx into google sheets and convert there.

## Re-run a batch after errors are fixed
Once you've fixed any problems with the batch ingest spreadsheet, save the updated version (make sure it's a .csv file!). Then upload the updated version into the DONUT dropbox. You may overwrite the previous version. DONUT will detect that a new .csv has been uploaded, and re-run the ingest.

**Need to edit metadata for works that you've already ingested? Go to [How to edit metadata in DONUT](https://github.com/nulib/next-generation-repository/wiki/How-to-edit-metadata-in-DONUT) next**

**Comment by davidschober** [comment]
Sample Batch Spreadsheet with descriptive headers 

[batch_ingest_template(2).xlsx](https://github.com/samvera-labs/hyrax-batch_ingest/files/2354477/batch_ingest_template.2.xlsx)

**Comment by afred** [comment]
This is out of scope for this repo. Our goal here will be to provide a framework for writing a custom "Reader" (or similar module) for reading Avalon's specific input format (i.e. a Avalon-specific CSV template). Look for future tickets on creating custom Readers for various formats.
